name: "Generate Documentation"
on:
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
      pip install sphinx_rtd_theme
      mkdir "/tmp/sphinx-log"
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"